const suma = (...numeros) => numeros.reduce((acum, numero) => acum += numero)
const resta = (...numeros) => numeros.reduce((acum, numero) => acum -= numero)
const multiplicar = (...numeros) => numeros.reduce((acum, numero) => acum *= numero)
const dividir = (...numeros) => numeros.reduce((acum, numero) => acum /= numero)
const pares = (...numeros) => numeros.filter(numero => numero % 2 == 0)
const impares = (...numeros) => numeros.filter(numero => numero % 2 !== 0)
const multiplo5 = (...numeros) => numeros.filter(numero => numero % 5 == 0)
const cuadrados = (...numeros) => numeros.map(numero => Math.pow(numero, 2))
const raices = (...numeros) => numeros.map(numero => Math.sqrt(numero).toFixed(2))
const euler = (...numeros) => numeros.map(numero => Math.exp(numero).toFixed(2))
const logaritmoBase10 = (...numeros) => numeros.map(numero => Math.log10(numero).toFixed(2))